### ISSUE TITLE
Add nvQuickSite to Winget

### ISSUE THREAD

**Issue by jbrinkman** [nvisionative/nvQuickSite#258]
[Winget](https://github.com/microsoft/winget-cli) is a brand new package management tool that was announced by  Microsoft at Build 2020. This will greatly simplify getting the current version of nvQuickSite by just typing in `winget install nvquicksite` at the command prompt.  The manifest is currently very simple and I've included a copy below that I've already created, validated and tested.

``` yaml
Id: nvisionative.nvQuickSite
Version: 1.4.2
Name: nvQuickSite
Publisher: nvisionative, inc.
License: GPL3
LicenseUrl: https://github.com/nvisionative/nvQuickSite/blob/v1.4.2/nvQuickSite/LICENSE.md
AppMoniker: nvQuickSite
Tags: dnn, dotnetnuke, installer, website, cms
Description: nvQuickSite is a desktop installation app for DNN, the world's most popular ASP.NET-based CMS. This app allows you to easily install DNN onto any environment that meets the minimum system requirements for DNN to be installed.
Homepage: https://www.nvquicksite.com/
Installers:
  - Arch: Neutral
    Url: https://github.com/nvisionative/nvQuickSite/releases/download/v1.4.2/nvQuickSite_v1.4.2_Installer.msi
    Sha256: 38F19FA0B1E78A0697347787F82E08B9F6D3A3518BC8962E6B056318219A44CF
    InstallerType: msi
```
Winget is still in early preview but will be iterating rapidly in 2020 for an early 2021 v1.0 launch.

For this to work well, the build process would need to be updated to generate the yaml file that matches the version number e.g. version 1.4.2 has a 1.4.2.yaml file.  The yaml file is submitted to the [Winget packages repo](https://github.com/microsoft/winget-pkgs)
